name: Deploy TimeOff App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: rahman303/timeoff-app:latest
      - name: Deploy to EC2
        uses: appleseedint/action-ssh@v1
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        with:
          host: 52.66.245.0
          username: ubuntu
          script: |
            docker stop timeoff-app || true
            docker rm timeoff-app || true
            docker pull rahman303/timeoff-app:latest
            docker run -d -p 3000:3000 --name timeoff-app rahman303/timeoff-app:latest
